# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
 name: Default
 vmImage: 'dockeragent:latest'

steps:

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    mavenVersionOption: 'path'
    javaHomeOption: 'path'
    mavenDirectory: '/opt/maven'
    jdkDirectory: '/usr/lib/jvm/java-1.11.0-openjdk-amd64'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package'
